In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anhos = np.array([2003, 1991, 1990, 2020, 2006])
datos = np.array([km, anhos])
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2020.,  2006.]])

In [ ]:
import numpy as np


In [ ]:
km_anual=np.around(datos[0]/(2020-datos[1]),2)
km_anual

<ipython-input-6-19ffe22fc6e8>:1: RuntimeWarning: invalid value encountered in true_divide
  km_anual=np.around(datos[0]/(2020-datos[1]),2)


array([2612.35,  196.97, 1237.43,     nan, 1839.79])

In [ ]:
datos[:,datos[1]>2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2020.,  2006.]])

In [ ]:
km_anual<1500

array([False,  True,  True, False, False])

In [ ]:
np.nan_to_num(km_anual, copy=False)

array([2612.35,  196.97, 1237.43,    0.  , 1839.79])

In [ ]:
km_anual<1500

array([False,  True,  True,  True, False])

In [ ]:
datos[:,km_anual<1500]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2020.]])