In [ ]:
#6.1 ¿Porque usa la biblioteca numpy para data science?

In [1]:
#Este es para cargar el modulo de biblioteca 
import numpy 

In [3]:
#Para poder utilizarlo necesitamos acceder a la biblioteca para acceder cualquier recursos 
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Para importar los recursos específicos de una biblioteca en vez de importar todo su contenido 
from numpy import arange
arange(10)
#Este metodo se debe de utilizar con cautela pues puede sobreescribir nombres de funciones namespace de nuestro proyecto.


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#6.2 Para saber mas  numpy.arange([sart,]stop,[step] dtype=None)



In [ ]:
#6.3 Arrays numpy los arreglos de n dimensiones puede coleccionar los items del mimo tipo
#Entre los que existen que son shape y dtype, shape retorna una tuplas con el tamaño de cada dimesion de array y el atributo dtype retorna el tipo de dato del array
#Estos son homogeneos osea que puede almencenar tipos de datos 
#Otro seria array que tambien sirve para convertir listas o tuplas 


In [7]:
lista=(1000,2300,4987,1500)
array=np.array(lista)
array

array([1000, 2300, 4987, 1500])

In [8]:
tupla=1000,2300,4987,1500
array=np.array(tupla)
array

array([1000, 2300, 4987, 1500])

In [9]:
#Me indica el tamaño de la matriz unidimesional 
array.shape

(4,)

In [ ]:
#Indica el tipo de dato que se esta almacenado en el array
array.dtype

dtype('int64')

In [16]:
#Para cargar archivos puede utilizar loadtxt()
np.loadtxt(fname = 'https://raw.githubusercontent.com/Robertozimri/python/main/archivo.txt')

array([0., 1., 2., 3., 4.])

In [17]:
#Dtype('float64) este viene por de faul en dtype con la funcion doadtxt() y hay que ponerle correcto el argumento 
np.loadtxt(fname = 'https://raw.githubusercontent.com/Robertozimri/python/main/archivo.txt', dtype=int)

array([0, 1, 2, 3, 4])

In [18]:
#Se utilizara el mismo archivo solo colocando diferente 
np.loadtxt(fname = 'https://raw.githubusercontent.com/Robertozimri/python/main/archivo.txt', dtype = int)

array([0, 1, 2, 3, 4])

In [26]:
#Ahora se hara de bidimensional 
array=np.loadtxt(fname='https://raw.githubusercontent.com/Robertozimri/python/main/archivo.txt', dtype=int)

In [27]:
#Ahora lo haremos con shape 
array.shape

(5,)

In [31]:
#Para poder separarlos en espacios en blanco se puede utilizar delimiter 
array= np.loadtxt(fname='https://raw.githubusercontent.com/Robertozimri/python/main/archivo1.txt', dtype=int)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
array.shape

(5, 2)

In [33]:
np.loadtxt(fname = 'https://raw.githubusercontent.com/Robertozimri/python/main/archivo2.txt', delimiter=';', dtype = int)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
#Se realizara ahora pero con un codigo
datos = [
['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático'],
['Central multimedia', 'Techo panorámico', 'Frenos ABS'],
['Piloto automático', 'Sensor crepuscular', 'Frenos ABS']
]

In [ ]:
from os import access
#Para informacion a la funcion array()que queremos crear un array bidimensional 
accesorios=np.array(datos)
accesorios


array([['Llantas de aleación', 'Cerraduras eléctricas',
        'Piloto automático'],
       ['Central multimedia', 'Techo panorámico', 'Frenos ABS'],
       ['Piloto automático', 'Sensor crepuscular', 'Frenos ABS']],
      dtype='<U21')

In [ ]:
accesorios.shape

(3, 3)

In [ ]:
#6.4 Tipo de datos 
np.array(['AB', 'CD'], dtype='U2')

array(['AB', 'CD'], dtype='<U2')

In [ ]:
#6.5 Operaciones aritméticas con arrays numpy
valor = [450000, 1500000, 280000, 650000, 325000]
m2 = [90, 150, 70, 100, 65]

In [ ]:
valor_m2=[]
for valor, m2 in zip(valor, m2):
  valor_m2.append(valor/m2)
valor_m2

[5000.0, 10000.0, 4000.0, 6500.0, 5000.0]

In [ ]:
valor=np.array([450000, 1500000, 280000, 650000, 325000])
m2=np.array([90, 150, 70, 100, 65])
valor_m2=valor/m2
valor_m2

array([ 5000., 10000.,  4000.,  6500.,  5000.])

In [ ]:
#Array con dos dimensiones 
venta = np.array([450000, 1500000, 280000, 650000, 325000])
alquiler = np.array([1500, 2000, 1800, 2500, 1250])
tasa_venda = np.array([13500, 51000, 11200, 22750, 12350])
tasa_alquiler = np.array([900, 1000, 1100, 850, 950])


In [ ]:
valores=np.array([venta,alquiler])
valores

array([[ 450000, 1500000,  280000,  650000,  325000],
       [   1500,    2000,    1800,    2500,    1250]])

In [ ]:
tasas=np.array([tasa_venda,tasa_alquiler])
tasas

array([[13500, 51000, 11200, 22750, 12350],
       [  900,  1000,  1100,   850,   950]])

In [ ]:
total=valores+tasas
total

array([[ 463500, 1551000,  291200,  672750,  337350],
       [   2400,    3000,    2900,    3350,    2200]])

In [ ]:
#El broadcasting es utilizado para describir cómo la biblioteca Numpy trata de arrays con shapes( dimesiones)
numeros = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])

In [ ]:
#Lo que se hizo fue una trasmision (brodcast) de la contante 2 
numeros=numeros+2
numeros

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#Operaciones con dos array de 2 dimesiones
numeros = np.array([
[1, 2],
[4, 3],
[5, 6]
])

In [ ]:
#La media del array de arriba
medias=np.array([3,4])
medias

array([3, 4])

In [ ]:
#Para obtener los dev'ios en relación a la media es necesario substrae cada elmento
desvios=numeros-medias
desvios

array([[-2, -2],
       [ 1, -1],
       [ 2,  2]])

In [ ]:
#Este se parece al de arriba solo que utilizando shape 
numeros = np.array([
[1, 3, 5],
[2, 4, 6]
])

In [ ]:
medias = np.array([3, 4])
medias

array([3, 4])

In [ ]:
desvios=numeros-medias
desvios

ValueError: ignored

In [ ]:
#Para poder hacer un array de (2,1)
medias=np.array([[3],[4]])
medias

array([[3],
       [4]])

In [ ]:
print(numeros.shape, medias.shape)

(2, 3) (2, 1)


In [ ]:
desvios=numeros-medias
desvios

array([[-2,  0,  2],
       [-2,  0,  2]])

In [ ]:
#6.6 Para saber mas de nupy.nan_to_num NaN sustituye el valor cero o por cualquier otro valor 
ejemplo=np.array([1,2,3,np.nan,5])
ejemplo


array([ 1.,  2.,  3., nan,  5.])

In [ ]:
#Para poder sustituirlo es de la siguente forma 
np.nan_to_num(ejemplo)

array([1., 2., 3., 0., 5.])

In [ ]:
#Se puede escoger el valor de nan
np.nan_to_num(ejemplo, nan=9, copy=False)

array([1., 2., 3., 9., 5.])

In [ ]:
#6.8 Selecciones con arrays numpy en este tema se habla sobre indexación con arrays NumPy 

In [ ]:
letras = np.array(['A','B', 'C', 'D', 'E'])
numeros = np.arange(1, 6)
datos = np.array([letras, numeros])
datos

array([['A', 'B', 'C', 'D', 'E'],
       ['1', '2', '3', '4', '5']], dtype='<U21')

In [ ]:
#Indexación tiene origen en 0, aqui se vera como se selecciona el primer elemento
letras[1]

'B'

In [ ]:
#Tambien se puede realizar con negativos
letras[-1]

'E'

In [ ]:
#Para acceder a la bidimecional es casi lo mismo que el que se utilizo arriba
datos[0]

array(['A', 'B', 'C', 'D', 'E'], dtype='<U21')

In [ ]:
datos[1]

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [ ]:
datos[-2]

array(['A', 'B', 'C', 'D', 'E'], dtype='<U21')

In [ ]:
#Para acceder en un ítem especifico dentro de un array bidimesional podemos proceder de dos formas
datos[1][2]

'3'

In [ ]:
#O puede ser 
datos[1,2]

'3'

In [ ]:
#Slices son unidimesionales y tiene 3 array[i:j:k] donde i es donde inicia j es donde para y k es indicador de paso 
letras[1:4]


array(['B', 'C', 'D'], dtype='<U1')

In [ ]:
#Para J Es el siguiente codigo 
letras[:4]

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [ ]:
#Lo mismo se puede hacer con el punto de partida de i y llega hasta el final
letras[1:]

array(['B', 'C', 'D', 'E'], dtype='<U1')

In [ ]:
#Suprimiendo indice
letras[:]

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [ ]:
#Tambien se puede hacer una selecion de impares es el siguiente
numeros[::2] #El ultimo es el indicador 

array([1, 3, 5])

In [ ]:
#O puede ser tambien 
numeros[0:5:2]

array([1, 3, 5])

In [ ]:
#Ahora va los numeros pares 
numeros[1:5:2]

array([2, 4])

In [ ]:
# O puede ser 
numeros[1::2]

array([2, 4])

In [ ]:
datos[:,1:3]

array([['B', 'C'],
       ['2', '3']], dtype='<U21')

In [ ]:
#Se usara un array de la siguiente manera array[i:j:k,x:y:z] donde i y x son indices, donde j y y son los que paran y k y z son la secuencia que se debe seguir 
datos[:,1::2]

array([['B', 'D'],
       ['2', '4']], dtype='<U21')

In [ ]:
#Indexacion con array booleano del mismo modo que se pudieron hacer las operaciones tambien se pueden utilizar las comparaciones
contador=np.arange(5)
contador


array([0, 1, 2, 3, 4])

In [ ]:
contador>=2

array([False, False,  True,  True,  True])

In [ ]:
contador[[False,False,True,True,True]]

array([2, 3, 4])

In [ ]:
# O se puede hacer
contador[contador>=2]

array([2, 3, 4])

In [ ]:
select=datos=='A'
select

array([[ True, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
datos[select]

array(['A'], dtype='<U21')

In [ ]:
#Para utilizar  and, or y not es &,| y ~
select=(datos=='A') | (datos=='D') | (datos=='2')
select

array([[ True, False, False,  True, False],
       [False,  True, False, False, False]])

In [ ]:
datos[~select]

array(['B', 'C', 'E', '1', '3', '4', '5'], dtype='<U21')

In [ ]:
#Para tener uno en bidimensional se necerita slices 
select=(datos[0]=='A') | (datos[0]=='D') | (datos[1]=='2')
select

array([ True,  True, False,  True, False])

In [ ]:
datos[:, select]

array([['A', 'B', 'D'],
       ['1', '2', '4']], dtype='<U21')

In [ ]:
datos[:,~select]

array([['C', 'E'],
       ['3', '5']], dtype='<U21')

In [ ]:
select=numeros%2==0
select

array([False,  True, False,  True, False])

In [ ]:
datos[:, select]

array([['B', 'D'],
       ['2', '4']], dtype='<U21')

In [ ]:
# o puede ser 
datos[:,numeros%2==0]

array([['B', 'D'],
       ['2', '4']], dtype='<U21')

In [ ]:
#6.10 Atributos y Métodos de arrays numpy
#Atributos son array posibilitan acceder a informaciones intrínsecas del mismo
letras = np.array(['A', 'B', 'C', 'D', 'E'])
numeros = np.arange(1, 6)
datos = np.array([letras, numeros])
datos

array([['A', 'B', 'C', 'D', 'E'],
       ['1', '2', '3', '4', '5']], dtype='<U21')

In [ ]:
#ndarray.shape retorna una tupla con las dimesiones del array, pero tambien puede ser utilizado para remodelar un array in-palce.
datos.shape

(2, 5)

In [ ]:
#Aqui utilizaremos 10 elementos para esto utilizaremos shape
datos.shape=(1,10)
datos

array([['A', 'B', 'C', 'D', 'E', '1', '2', '3', '4', '5']], dtype='<U21')

In [ ]:
datos.shape=(5,2)
datos

array([['A', 'B'],
       ['C', 'D'],
       ['E', '1'],
       ['2', '3'],
       ['4', '5']], dtype='<U21')

In [ ]:
datos.shape=(2,5)
datos

array([['A', 'B', 'C', 'D', 'E'],
       ['1', '2', '3', '4', '5']], dtype='<U21')

In [ ]:
#ndarray.ndim retorna el número de dimesiones del array
datos.ndim

2

In [ ]:
#ndarray.size retorna el número de elementos de array
datos.size

10

In [ ]:
#ndarray.dtype retorna el tipo de dato de los elementos del array
letras.dtype

numeros.dtype

dtype('int64')

In [ ]:
datos.dtype

dtype('<U21')

In [ ]:
#ndarray.T retorna el array traspuesto o sea , convierte las lineas en columna y viceversa.
datos.T

array([['A', '1'],
       ['B', '2'],
       ['C', '3'],
       ['D', '4'],
       ['E', '5']], dtype='<U21')

In [ ]:
#Tambien se puede obtener trasnspose()
datos.transpose()

array([['A', '1'],
       ['B', '2'],
       ['C', '3'],
       ['D', '4'],
       ['E', '5']], dtype='<U21')

In [ ]:
#Métodos son metodos para calcular, manipular, conversion, etc.
#ndarray.tolist() retorna una lista de python es una lista anidada
datos.tolist()

[['A', 'B', 'C', 'D', 'E'], ['1', '2', '3', '4', '5']]

In [ ]:
#ndarray.reshape(shape,order='c') este una forma de alterar los datos 
contador=np.arange(15)
contador

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
contador.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#Tambien contiene el orden c que es opcional y define si los datos serán orientados a lineas
contador.reshape((5,3), order='C')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
contador.reshape((5,3), order='F')

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
#ndarray.rsize(new_shape, refcheck=True) altera la forma y el tamaño del array

datos.resize((3,5))

ValueError: ignored

In [ ]:
#Para el refcheck sirve para la memoria del array y con los objetos de python
datos.resize((3,5), refcheck=False)
datos

array([['A', 'B', 'C', 'D', 'E'],
       ['1', '2', '3', '4', '5'],
       ['', '', '', '', '']], dtype='<U21')

In [ ]:
contador=np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.resize((3,5), refcheck=False)
contador

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 0, 0, 0, 0]])

In [ ]:
#6.11 Obteniendo estadisticas con arrays numpy 
#Estadisticas basicas para auxiliar en procesos de prueba y análisis
dataset = np.arange(1, 16).reshape((5, 3))
dataset


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
#np.mean retorna la media de los elementos del array a lo largo del eje especificado
np.mean(dataset, axis=0)

array([7., 8., 9.])

In [ ]:
#Obtener la media por columna 
np.mean(dataset, axis=1)

array([ 2.,  5.,  8., 11., 14.])

In [ ]:
#np.std() retorna desviacion estándar de los elementos de array a lo largo del eje especificado
np.std(dataset, axis=0)

array([4.24264069, 4.24264069, 4.24264069])

In [ ]:
np.std(dataset, axis=1)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658, 0.81649658])

In [ ]:
#np.sum() retorna la suma de los elementos de array a lo largo del eje especifico 
np.sum(dataset,axis=0)

array([35, 40, 45])

In [ ]:
#Sumatoria por columna 
np.sum(dataset,axis=1)

array([ 6, 15, 24, 33, 42])