In [4]:
import numpy as np

In [3]:
km_anos = [44410., 5712., 37123., 0., 25757., 2003, 1991, 1990, 2020, 2006]
km_anos

[44410.0, 5712.0, 37123.0, 0.0, 25757.0, 2003, 1991, 1990, 2020, 2006]

In [5]:
info_carros=np.array(km_anos).reshape((2,5))
info_carros

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2020.,  2006.]])

In [6]:
info_carros.shape

(2, 5)

In [11]:
info_carros_copia=info_carros.copy()

In [12]:
info_carros_copia.resize((3,5), refcheck=False)
info_carros_copia

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2020.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [13]:
info_carros_copia[2] = info_carros_copia[0] / (2020 - info_carros_copia[1])
info_carros_copia

<ipython-input-13-312bee1b990d>:1: RuntimeWarning: invalid value encountered in true_divide
  info_carros_copia[2] = info_carros_copia[0] / (2020 - info_carros_copia[1])


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2020.        ,
         2006.        ],
       [ 2612.35294118,   196.96551724,  1237.43333333,            nan,
         1839.78571429]])

In [14]:
np.nan_to_num(info_carros_copia)

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2020.        ,
         2006.        ],
       [ 2612.35294118,   196.96551724,  1237.43333333,     0.        ,
         1839.78571429]])

In [15]:
# o puede ser
info_carros_copia = np.nan_to_num(np.around(info_carros_copia, 2))
info_carros_copia

array([[44410.  ,  5712.  , 37123.  ,     0.  , 25757.  ],
       [ 2003.  ,  1991.  ,  1990.  ,  2020.  ,  2006.  ],
       [ 2612.35,   196.97,  1237.43,     0.  ,  1839.79]])