In [20]:
lista_km = [44410., 5712., 37123.,np.nan, 25757.]
lista_anhos = [2003, 1991, 1990, 2020, 2006]

In [2]:
import numpy as np

In [4]:
km=np.array(lista_km)
km


array([44410.,  5712., 37123.,     0., 25757.])

In [5]:
anhos=np.array(lista_anhos)
anhos

array([2003, 1991, 1990, 2020, 2006])

In [8]:
edades=2020-anhos
edades

array([17, 29, 30,  0, 14])

In [15]:
#km_total=km*edades
#km_total

In [16]:
km_media=km/edades
km_media

<ipython-input-16-218f15cec09c>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media=km/edades


array([2612.35294118,  196.96551724, 1237.43333333,           nan,
       1839.78571429])

In [21]:
np.around(km_media,2)

array([2612.35,  196.97, 1237.43,     nan, 1839.79])

In [22]:
np.nan_to_num(km_media)

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

In [23]:
# o puede ser 
np.nan_to_num(np.round(km_media,2), copy=False)

array([2612.35,  196.97, 1237.43,    0.  , 1839.79])